import React from 'react';
import { Program } from '../types';

interface PrintableScheduleProps {
  program: Program;
  includeSpeakers?: boolean;
  includeDetails?: boolean;
}

const PrintableSchedule: React.FC<PrintableScheduleProps> = ({
  program,
  includeSpeakers = true,
  includeDetails = true
}) => {
  // Time Helper
  const timeToMinutes = (time: string): number => {
    if (!time) return 0;
    const [h, m] = time.split(':').map(Number);
    return (h * 60) + m;
  };

  const minutesToTime = (minutes: number): string => {
    const h = Math.floor(minutes / 60) % 24;
    const m = minutes % 60;
    const ampm = h >= 12 ? 'PM' : 'AM';
    const h12 = h % 12 || 12;
    return `${h12}:${m.toString().padStart(2, '0')} ${ampm}`;
  };

  const startMinutes = timeToMinutes(program.startTime || "09:00");
  let runningMinutes = startMinutes;

  return (
    <div id="printable-area" className="only-print bg-white text-black">
      {/* Header */}
      <div className="border-b-2 border-black pb-2 mb-3">
        <h1 className="text-2xl font-bold mb-1">{program.title}</h1>
        <div className="flex justify-between items-end">
          <div>
            <p className="text-base text-gray-600 font-medium">{program.subtitle}</p>
            <p className="text-xs mt-0.5">Date: {new Date(program.date).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
          </div>
          <div className="text-right">
            <p className="text-xs">Start Time: {minutesToTime(startMinutes)}</p>
            <p className="text-xs">Total Sessions: {program.slots.length}</p>
          </div>
        </div>
      </div>

      {/* Schedule Table */}
      <table className="w-full text-left border-collapse">
        <thead>
          <tr className="border-b-2 border-black">
            <th className="py-1 w-20 font-bold text-xs">Time</th>
            <th className="py-1 font-bold text-xs">Session / Activity</th>
            <th className="py-1 w-24 font-bold text-xs">Duration</th>
          </tr>
        </thead>
        <tbody>
          {program.slots.map((slot) => {
            const currentStart = runningMinutes;
            runningMinutes += slot.durationMinutes;

            return (
              <tr key={slot.id} className="border-b border-gray-200 break-inside-avoid">
                <td className="py-1.5 align-top font-mono text-xs">
                  {minutesToTime(currentStart)}
                </td>
                <td className="py-1.5 align-top px-2">
                  <div className="font-bold text-sm">{slot.title}</div>
                  {includeSpeakers && slot.speaker && (
                    <div className="text-xs font-semibold text-gray-700 mt-0.5">{slot.speaker}</div>
                  )}
                  <div className="mt-0.5 inline-block px-1.5 py-0.5 border border-gray-300 rounded-full text-[9px] uppercase tracking-wide font-medium">
                    {slot.type}
                  </div>
                  {includeDetails && slot.details && (
                    <div className="text-xs text-gray-600 mt-1 leading-tight">
                      {slot.details}
                    </div>
                  )}
                </td>
                <td className="py-1.5 align-top text-right font-mono text-xs">
                  {slot.durationMinutes} min
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      {/* Footer */}
      <div className="mt-4 pt-2 border-t border-gray-300 text-center text-[10px] text-gray-500">
        Generated by Kairon
      </div>
    </div>
  );
};

export default PrintableSchedule;